name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (skip if none)
        run: npm test --if-present -- --passWithNoTests

      - name: Build React app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Use the private key from GitHub secrets
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Set default SSH port if not provided
          SSH_PORT="${{ secrets.SSH_PORT }}"
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi

          # Add server to known_hosts to avoid interactive prompt
          ssh-keyscan -p $SSH_PORT -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync + atomic symlink
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          SSH_PORT="${{ secrets.SSH_PORT }}"
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi
          RELEASE="release-$(date +%s)"
          echo "Deploying to ${DEPLOY_PATH}/releases/$RELEASE"

          # Sync build folder to server
          rsync -e "ssh -p $SSH_PORT" -avz --delete build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${DEPLOY_PATH}/releases/$RELEASE/

          # Update 'current' symlink atomically
          ssh -p $SSH_PORT ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "set -e
            ln -sfn ${DEPLOY_PATH}/releases/$RELEASE ${DEPLOY_PATH}/current
            sudo chown -R www-data:www-data ${DEPLOY_PATH}/current || true
            cd ${DEPLOY_PATH}/releases
            ls -1tr | head -n -5 | xargs -r rm -rf || true
          "
