name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (skip if none)
        run: npm test --if-present -- --passWithNoTests

      - name: Build React app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via rsync + atomic symlink
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          # Default SSH port
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi

          RELEASE="release-$(date +%s)"
          echo "Deploying to ${DEPLOY_PATH}/releases/$RELEASE"

          # Add server to known_hosts to avoid host key verification failure
          ssh-keyscan -p $SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts

          # Sync build folder to server
          rsync -avz --delete -e "ssh -p $SSH_PORT" build/ $SSH_USER@$SSH_HOST:${DEPLOY_PATH}/releases/$RELEASE/

          # Update 'current' symlink atomically
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "set -e
            ln -sfn ${DEPLOY_PATH}/releases/$RELEASE ${DEPLOY_PATH}/current
            sudo chown -R www-data:www-data ${DEPLOY_PATH}/current || true
            cd ${DEPLOY_PATH}/releases
            ls -1tr | head -n -5 | xargs -r rm -rf || true
          "
